name: Github Action Maven Build Example

on:
  push:
    branches: [ master ]
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the branch
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@1
        with:
          java-version: 1.8
       
      - name: Build the Maven Project
        run: mvn -B package --file pom.xml
      
      - name: List out the directory
        run: ls -a
        
      - name: whats in Target Folder
        run: |
            cd target
            ls -ltr
